// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wntnuwmssmnszknhodse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudG51d21zc21uc3prbmhvZHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODE1OTQsImV4cCI6MjA2MTE1NzU5NH0.MGJh8HLw-O3dM3t2CwMFEJ9ubjcOUtW_paXPGL0-3ME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);